import type { it } from "../it";

export const email: (typeof it)["email"] = {
  verifyEmail: {
    subject: "Your Car2ne verification code",
    heading: "Verify your email",
    body:
      "Hi {name},\n\nthanks for signing up to Car2ne! Use the code below to verify your email address. The code is valid for 10 minutes.\n\nIf you didn't create this account, you can safely ignore this email.",
  },
  passwordReset: {
    subject: "Your password reset code",
    heading: "Reset your password",
    body:
      "Hi {name},\n\nwe received a request to reset the password for your Car2ne account. Use the code below to choose a new one. The code is valid for 10 minutes.\n\nIf you didn't request this, you can safely ignore this email: your password will stay unchanged.",
  },
  mfaEnabled: {
    subject: "Two-factor authentication enabled",
    heading: "Two-factor authentication enabled",
    body:
      "Hi {name},\n\ntwo-factor authentication has been enabled on your Car2ne account. From now on, alongside your password, you'll be asked for a code generated by your authenticator app to sign in.\n\nIf you didn't enable this, please contact us immediately.",
    ctaLabel: "Go to your profile",
  },
  mfaDisabled: {
    subject: "Two-factor authentication disabled",
    heading: "Two-factor authentication disabled",
    body:
      "Hi {name},\n\ntwo-factor authentication has been disabled on your Car2ne account. From now on, your password alone will be enough to sign in.\n\nIf you didn't disable this, please contact us immediately.",
    ctaLabel: "Go to your profile",
  },
  accountDeleted: {
    subject: "Your Car2ne account has been deleted",
    heading: "Account deleted",
    body:
      "Hi {name},\n\nwe're confirming that your Car2ne account has been deleted at your request. Your personal data has been removed and you will no longer be able to sign in with this account.\n\nIf you didn't request this, please contact us immediately.",
    ctaLabel: "",
  },
};
